"""Add daily extraction fields to VaultFile

Revision ID: 04be8156a34e
Revises: 84c005084b87
Create Date: 2026-07-08 16:38:15.864133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04be8156a34e'
down_revision: Union[str, None] = '84c005084b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vault_files', sa.Column('last_extracted_content', sa.Text(), nullable=True))
    op.add_column('vault_files', sa.Column('last_extracted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vault_files', 'last_extracted_at')
    op.drop_column('vault_files', 'last_extracted_content')
    # ### end Alembic commands ###
