"""Add accounts and categories

Revision ID: 36c643091c80
Revises: 6e3b68412e0d
Create Date: 2026-06-09 23:36:19.029208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '36c643091c80'
down_revision: Union[str, None] = '6e3b68412e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('CHECKING', 'SAVINGS', 'CREDIT_CARD', 'INVESTMENT', 'LOAN', name='accounttype'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['finance_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('chat_sessions', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.execute("UPDATE chat_sessions SET is_archived = FALSE WHERE is_archived IS NULL")
    op.alter_column('chat_sessions', 'is_archived', nullable=False)
    op.add_column('finance_expenses', sa.Column('account_id', sa.Uuid(), nullable=True))
    op.add_column('finance_expenses', sa.Column('category_id', sa.Uuid(), nullable=True))
    op.alter_column('finance_expenses', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'finance_expenses', 'finance_accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'finance_expenses', 'finance_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finance_expenses', type_='foreignkey')
    op.drop_constraint(None, 'finance_expenses', type_='foreignkey')
    op.alter_column('finance_expenses', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('finance_expenses', 'category_id')
    op.drop_column('finance_expenses', 'account_id')
    op.drop_column('chat_sessions', 'is_archived')
    op.drop_table('finance_categories')
    op.drop_table('finance_accounts')
    # ### end Alembic commands ###
