"""Add user_id FKs to all data tables

Revision ID: 71fb288f8d09
Revises: g002
Create Date: 2026-06-21 13:21:32.099562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71fb288f8d09'
down_revision: Union[str, None] = 'g002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE agents CASCADE')
    op.execute('TRUNCATE TABLE business_events CASCADE')
    op.execute('TRUNCATE TABLE calendar_events CASCADE')
    op.execute('TRUNCATE TABLE captures CASCADE')
    op.execute('TRUNCATE TABLE career_events CASCADE')
    op.execute('TRUNCATE TABLE chat_messages CASCADE')
    op.execute('TRUNCATE TABLE chat_sessions CASCADE')
    op.execute('TRUNCATE TABLE content_items CASCADE')
    op.execute('TRUNCATE TABLE finance_accounts CASCADE')
    op.execute('TRUNCATE TABLE finance_bills CASCADE')
    op.execute('TRUNCATE TABLE finance_categories CASCADE')
    op.execute('TRUNCATE TABLE finance_expenses CASCADE')
    op.execute('TRUNCATE TABLE finance_goals CASCADE')
    op.execute('TRUNCATE TABLE finance_income CASCADE')
    op.execute('TRUNCATE TABLE finance_investments CASCADE')
    op.execute('TRUNCATE TABLE finance_loans CASCADE')
    op.execute('TRUNCATE TABLE finance_snapshots CASCADE')
    op.execute('TRUNCATE TABLE finance_transfers CASCADE')
    op.execute('TRUNCATE TABLE google_fit_metrics CASCADE')
    op.execute('TRUNCATE TABLE health_food_items CASCADE')
    op.execute('TRUNCATE TABLE health_goals CASCADE')
    op.execute('TRUNCATE TABLE health_habit_checks CASCADE')
    op.execute('TRUNCATE TABLE health_habits CASCADE')
    op.execute('TRUNCATE TABLE health_logs CASCADE')
    op.execute('TRUNCATE TABLE health_workout_sessions CASCADE')
    op.execute('TRUNCATE TABLE health_workout_sets CASCADE')
    op.execute('TRUNCATE TABLE integration_credentials CASCADE')
    op.execute('TRUNCATE TABLE job_opportunities CASCADE')
    op.execute('TRUNCATE TABLE push_subscriptions CASCADE')
    op.execute('TRUNCATE TABLE skill_inventory CASCADE')
    op.execute('TRUNCATE TABLE vault_chunks CASCADE')
    op.execute('TRUNCATE TABLE vault_conflicts CASCADE')
    op.execute('TRUNCATE TABLE vault_files CASCADE')
    op.add_column('agents', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    op.create_foreign_key(None, 'agents', 'users', ['user_id'], ['id'])
    op.add_column('business_events', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_business_events_user_id'), 'business_events', ['user_id'], unique=False)
    op.create_foreign_key(None, 'business_events', 'users', ['user_id'], ['id'])
    op.add_column('calendar_events', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.alter_column('calendar_events', 'google_event_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('calendar_events', 'title',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('calendar_events', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('calendar_events', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('calendar_events', 'location',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('calendar_events', 'status',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'confirmed'::text"))
    op.alter_column('calendar_events', 'html_link',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('calendar_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('calendar_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_calendar_events_start', table_name='calendar_events')
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_foreign_key(None, 'calendar_events', 'users', ['user_id'], ['id'])
    op.add_column('captures', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.alter_column('captures', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_captures_created_at', table_name='captures')
    op.create_index(op.f('ix_captures_user_id'), 'captures', ['user_id'], unique=False)
    op.create_foreign_key(None, 'captures', 'users', ['user_id'], ['id'])
    op.add_column('career_events', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_career_events_user_id'), 'career_events', ['user_id'], unique=False)
    op.create_foreign_key(None, 'career_events', 'users', ['user_id'], ['id'])
    op.add_column('chat_messages', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'users', ['user_id'], ['id'])
    op.add_column('chat_sessions', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'])
    op.add_column('content_items', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_content_items_user_id'), 'content_items', ['user_id'], unique=False)
    op.create_foreign_key(None, 'content_items', 'users', ['user_id'], ['id'])
    op.add_column('finance_accounts', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_finance_accounts_user_id'), 'finance_accounts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'finance_accounts', 'users', ['user_id'], ['id'])
    op.add_column('finance_bills', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_finance_bills_user_id'), 'finance_bills', ['user_id'], unique=False)
    op.create_foreign_key(None, 'finance_bills', 'users', ['user_id'], ['id'])
    op.add_column('finance_categories', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_finance_categories_user_id'), 'finance_categories', ['user_id'], unique=False)
    op.create_foreign_key(None, 'finance_categories', 'users', ['user_id'], ['id'])
    op.add_column('finance_expenses', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_finance_expenses_user_id'), 'finance_expenses', ['user_id'], unique=False)
    op.create_foreign_key(None, 'finance_expenses', 'users', ['user_id'], ['id'])
    op.add_column('finance_goals', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_finance_goals_user_id'), 'finance_goals', ['user_id'], unique=False)
    op.create_foreign_key(None, 'finance_goals', 'users', ['user_id'], ['id'])
    op.add_column('finance_income', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_finance_income_user_id'), 'finance_income', ['user_id'], unique=False)
    op.create_foreign_key(None, 'finance_income', 'users', ['user_id'], ['id'])
    op.add_column('finance_investments', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_finance_investments_user_id'), 'finance_investments', ['user_id'], unique=False)
    op.create_foreign_key(None, 'finance_investments', 'users', ['user_id'], ['id'])
    op.add_column('finance_loans', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_finance_loans_user_id'), 'finance_loans', ['user_id'], unique=False)
    op.create_foreign_key(None, 'finance_loans', 'users', ['user_id'], ['id'])
    op.add_column('finance_snapshots', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_finance_snapshots_user_id'), 'finance_snapshots', ['user_id'], unique=False)
    op.create_foreign_key(None, 'finance_snapshots', 'users', ['user_id'], ['id'])
    op.add_column('finance_transfers', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_finance_transfers_user_id'), 'finance_transfers', ['user_id'], unique=False)
    op.create_foreign_key(None, 'finance_transfers', 'users', ['user_id'], ['id'])
    op.add_column('google_fit_metrics', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.alter_column('google_fit_metrics', 'date',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('google_fit_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('google_fit_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_google_fit_metrics_date', table_name='google_fit_metrics')
    op.create_index(op.f('ix_google_fit_metrics_user_id'), 'google_fit_metrics', ['user_id'], unique=False)
    op.create_foreign_key(None, 'google_fit_metrics', 'users', ['user_id'], ['id'])
    op.add_column('health_food_items', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_health_food_items_user_id'), 'health_food_items', ['user_id'], unique=False)
    op.create_foreign_key(None, 'health_food_items', 'users', ['user_id'], ['id'])
    op.add_column('health_goals', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_health_goals_user_id'), 'health_goals', ['user_id'], unique=False)
    op.create_foreign_key(None, 'health_goals', 'users', ['user_id'], ['id'])
    op.add_column('health_habit_checks', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_constraint('uq_habit_check_day', 'health_habit_checks', type_='unique')
    op.create_index(op.f('ix_health_habit_checks_user_id'), 'health_habit_checks', ['user_id'], unique=False)
    op.create_foreign_key(None, 'health_habit_checks', 'users', ['user_id'], ['id'])
    op.add_column('health_habits', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_health_habits_user_id'), 'health_habits', ['user_id'], unique=False)
    op.create_foreign_key(None, 'health_habits', 'users', ['user_id'], ['id'])
    op.add_column('health_logs', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_health_logs_user_id'), 'health_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'health_logs', 'users', ['user_id'], ['id'])
    op.add_column('health_workout_sessions', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_health_workout_sessions_user_id'), 'health_workout_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'health_workout_sessions', 'users', ['user_id'], ['id'])
    op.add_column('health_workout_sets', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_health_workout_sets_user_id'), 'health_workout_sets', ['user_id'], unique=False)
    op.create_foreign_key(None, 'health_workout_sets', 'users', ['user_id'], ['id'])
    op.add_column('integration_credentials', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_integration_credentials_user_id'), 'integration_credentials', ['user_id'], unique=False)
    op.create_foreign_key(None, 'integration_credentials', 'users', ['user_id'], ['id'])
    op.add_column('job_opportunities', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_job_opportunities_user_id'), 'job_opportunities', ['user_id'], unique=False)
    op.create_foreign_key(None, 'job_opportunities', 'users', ['user_id'], ['id'])
    op.add_column('push_subscriptions', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'push_subscriptions', 'users', ['user_id'], ['id'])
    op.add_column('skill_inventory', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_skill_inventory_user_id'), 'skill_inventory', ['user_id'], unique=False)
    op.create_foreign_key(None, 'skill_inventory', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'picture_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('users', 'auth_provider',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'email'::text"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('vault_chunks', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_vault_chunks_user_id'), 'vault_chunks', ['user_id'], unique=False)
    op.create_foreign_key(None, 'vault_chunks', 'users', ['user_id'], ['id'])
    op.add_column('vault_conflicts', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_vault_conflicts_user_id'), 'vault_conflicts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'vault_conflicts', 'users', ['user_id'], ['id'])
    op.add_column('vault_files', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_vault_files_user_id'), 'vault_files', ['user_id'], unique=False)
    op.create_foreign_key(None, 'vault_files', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vault_files', type_='foreignkey')
    op.drop_index(op.f('ix_vault_files_user_id'), table_name='vault_files')
    op.drop_column('vault_files', 'user_id')
    op.drop_constraint(None, 'vault_conflicts', type_='foreignkey')
    op.drop_index(op.f('ix_vault_conflicts_user_id'), table_name='vault_conflicts')
    op.drop_column('vault_conflicts', 'user_id')
    op.drop_constraint(None, 'vault_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_vault_chunks_user_id'), table_name='vault_chunks')
    op.drop_column('vault_chunks', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'auth_provider',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'email'::text"))
    op.alter_column('users', 'picture_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'skill_inventory', type_='foreignkey')
    op.drop_index(op.f('ix_skill_inventory_user_id'), table_name='skill_inventory')
    op.drop_column('skill_inventory', 'user_id')
    op.drop_constraint(None, 'push_subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_column('push_subscriptions', 'user_id')
    op.drop_constraint(None, 'job_opportunities', type_='foreignkey')
    op.drop_index(op.f('ix_job_opportunities_user_id'), table_name='job_opportunities')
    op.drop_column('job_opportunities', 'user_id')
    op.drop_constraint(None, 'integration_credentials', type_='foreignkey')
    op.drop_index(op.f('ix_integration_credentials_user_id'), table_name='integration_credentials')
    op.drop_column('integration_credentials', 'user_id')
    op.drop_constraint(None, 'health_workout_sets', type_='foreignkey')
    op.drop_index(op.f('ix_health_workout_sets_user_id'), table_name='health_workout_sets')
    op.drop_column('health_workout_sets', 'user_id')
    op.drop_constraint(None, 'health_workout_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_health_workout_sessions_user_id'), table_name='health_workout_sessions')
    op.drop_column('health_workout_sessions', 'user_id')
    op.drop_constraint(None, 'health_logs', type_='foreignkey')
    op.drop_index(op.f('ix_health_logs_user_id'), table_name='health_logs')
    op.drop_column('health_logs', 'user_id')
    op.drop_constraint(None, 'health_habits', type_='foreignkey')
    op.drop_index(op.f('ix_health_habits_user_id'), table_name='health_habits')
    op.drop_column('health_habits', 'user_id')
    op.drop_constraint(None, 'health_habit_checks', type_='foreignkey')
    op.drop_index(op.f('ix_health_habit_checks_user_id'), table_name='health_habit_checks')
    op.create_unique_constraint('uq_habit_check_day', 'health_habit_checks', ['habit_id', 'check_date'])
    op.drop_column('health_habit_checks', 'user_id')
    op.drop_constraint(None, 'health_goals', type_='foreignkey')
    op.drop_index(op.f('ix_health_goals_user_id'), table_name='health_goals')
    op.drop_column('health_goals', 'user_id')
    op.drop_constraint(None, 'health_food_items', type_='foreignkey')
    op.drop_index(op.f('ix_health_food_items_user_id'), table_name='health_food_items')
    op.drop_column('health_food_items', 'user_id')
    op.drop_constraint(None, 'google_fit_metrics', type_='foreignkey')
    op.drop_index(op.f('ix_google_fit_metrics_user_id'), table_name='google_fit_metrics')
    op.create_index('ix_google_fit_metrics_date', 'google_fit_metrics', ['date'], unique=False)
    op.alter_column('google_fit_metrics', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('google_fit_metrics', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('google_fit_metrics', 'date',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('google_fit_metrics', 'user_id')
    op.drop_constraint(None, 'finance_transfers', type_='foreignkey')
    op.drop_index(op.f('ix_finance_transfers_user_id'), table_name='finance_transfers')
    op.drop_column('finance_transfers', 'user_id')
    op.drop_constraint(None, 'finance_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_finance_snapshots_user_id'), table_name='finance_snapshots')
    op.drop_column('finance_snapshots', 'user_id')
    op.drop_constraint(None, 'finance_loans', type_='foreignkey')
    op.drop_index(op.f('ix_finance_loans_user_id'), table_name='finance_loans')
    op.drop_column('finance_loans', 'user_id')
    op.drop_constraint(None, 'finance_investments', type_='foreignkey')
    op.drop_index(op.f('ix_finance_investments_user_id'), table_name='finance_investments')
    op.drop_column('finance_investments', 'user_id')
    op.drop_constraint(None, 'finance_income', type_='foreignkey')
    op.drop_index(op.f('ix_finance_income_user_id'), table_name='finance_income')
    op.drop_column('finance_income', 'user_id')
    op.drop_constraint(None, 'finance_goals', type_='foreignkey')
    op.drop_index(op.f('ix_finance_goals_user_id'), table_name='finance_goals')
    op.drop_column('finance_goals', 'user_id')
    op.drop_constraint(None, 'finance_expenses', type_='foreignkey')
    op.drop_index(op.f('ix_finance_expenses_user_id'), table_name='finance_expenses')
    op.drop_column('finance_expenses', 'user_id')
    op.drop_constraint(None, 'finance_categories', type_='foreignkey')
    op.drop_index(op.f('ix_finance_categories_user_id'), table_name='finance_categories')
    op.drop_column('finance_categories', 'user_id')
    op.drop_constraint(None, 'finance_bills', type_='foreignkey')
    op.drop_index(op.f('ix_finance_bills_user_id'), table_name='finance_bills')
    op.drop_column('finance_bills', 'user_id')
    op.drop_constraint(None, 'finance_accounts', type_='foreignkey')
    op.drop_index(op.f('ix_finance_accounts_user_id'), table_name='finance_accounts')
    op.drop_column('finance_accounts', 'user_id')
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.drop_index(op.f('ix_content_items_user_id'), table_name='content_items')
    op.drop_column('content_items', 'user_id')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'user_id')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'user_id')
    op.drop_constraint(None, 'career_events', type_='foreignkey')
    op.drop_index(op.f('ix_career_events_user_id'), table_name='career_events')
    op.drop_column('career_events', 'user_id')
    op.drop_constraint(None, 'captures', type_='foreignkey')
    op.drop_index(op.f('ix_captures_user_id'), table_name='captures')
    op.create_index('ix_captures_created_at', 'captures', ['created_at'], unique=False)
    op.alter_column('captures', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('captures', 'user_id')
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.create_index('ix_calendar_events_start', 'calendar_events', ['start_time'], unique=False)
    op.alter_column('calendar_events', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('calendar_events', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('calendar_events', 'html_link',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('calendar_events', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'confirmed'::text"))
    op.alter_column('calendar_events', 'location',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('calendar_events', 'end_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('calendar_events', 'start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('calendar_events', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('calendar_events', 'google_event_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('calendar_events', 'user_id')
    op.drop_constraint(None, 'business_events', type_='foreignkey')
    op.drop_index(op.f('ix_business_events_user_id'), table_name='business_events')
    op.drop_column('business_events', 'user_id')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.drop_column('agents', 'user_id')
    # ### end Alembic commands ###
