"""Add Business model and business_id to BusinessEvent

Revision ID: 755c6a00719d
Revises: h009
Create Date: 2026-06-22 21:54:50.010990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '755c6a00719d'
down_revision: Union[str, None] = 'h009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_user_id'), 'businesses', ['user_id'], unique=False)
    op.drop_index('ix_budget_limits_user_id', table_name='budget_limits')
    op.add_column('business_events', sa.Column('business_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_business_events_business_id'), 'business_events', ['business_id'], unique=False)
    op.create_foreign_key(None, 'business_events', 'businesses', ['business_id'], ['id'])
    op.drop_constraint('content_campaigns_user_id_fkey', 'content_campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'content_campaigns', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_content_items_campaign_id', 'content_items', type_='foreignkey')
    op.create_foreign_key(None, 'content_items', 'content_campaigns', ['campaign_id'], ['id'])
    op.drop_constraint('fk_oauth_states_user_id', 'oauth_states', type_='foreignkey')
    op.create_foreign_key(None, 'oauth_states', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_subscription_user', 'subscriptions', type_='unique')
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_unique_constraint('uq_subscription_user', 'subscriptions', ['user_id'])
    op.drop_constraint(None, 'oauth_states', type_='foreignkey')
    op.create_foreign_key('fk_oauth_states_user_id', 'oauth_states', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.create_foreign_key('fk_content_items_campaign_id', 'content_items', 'content_campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'content_campaigns', type_='foreignkey')
    op.create_foreign_key('content_campaigns_user_id_fkey', 'content_campaigns', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'business_events', type_='foreignkey')
    op.drop_index(op.f('ix_business_events_business_id'), table_name='business_events')
    op.drop_column('business_events', 'business_id')
    op.create_index('ix_budget_limits_user_id', 'budget_limits', ['user_id'], unique=False)
    op.drop_index(op.f('ix_businesses_user_id'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
