"""add finance_transfers and income account_id

Revision ID: 7863ebb3c628
Revises: 78b55e0b0432
Create Date: 2026-06-10 13:42:13.952362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7863ebb3c628'
down_revision: Union[str, None] = '78b55e0b0432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_transfers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('from_account_id', sa.Uuid(), nullable=False),
    sa.Column('to_account_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_account_id'], ['finance_accounts.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['finance_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('finance_income', sa.Column('account_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_finance_income_account_id', 'finance_income', 'finance_accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_finance_income_account_id', 'finance_income', type_='foreignkey')
    op.drop_column('finance_income', 'account_id')
    op.drop_table('finance_transfers')
    # ### end Alembic commands ###
