"""restore_captures_table

Revision ID: 78b55e0b0432
Revises: e17a40fc9ddb
Create Date: 2026-06-10 03:25:08.440367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '78b55e0b0432'
down_revision: Union[str, None] = 'e17a40fc9ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # `captures` table was created in 0002_add_captures, then accidentally dropped
    # by 6e3b68412e0d_add_missing_tables (an autogenerated migration whose upgrade()
    # mistakenly contained the inverse/downgrade operations for this table). The
    # Capture model (app/models/captures.py) and Quick Capture feature still rely
    # on this table, causing `relation "captures" does not exist` 500s. Recreate it.
    op.create_table('captures',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('raw_text', sa.TEXT(), nullable=False),
        sa.Column('processed', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='captures_pkey')
    )
    op.create_index('ix_captures_created_at', 'captures', ['created_at'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_captures_created_at', table_name='captures')
    op.drop_table('captures')
