"""Add user_id to daily token usage

Revision ID: 803135c34013
Revises: 71fb288f8d09
Create Date: 2026-06-21 13:34:19.553581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803135c34013'
down_revision: Union[str, None] = '71fb288f8d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE daily_token_usage CASCADE')
    op.add_column('daily_token_usage', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'daily_token_usage', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_token_usage', type_='foreignkey')
    op.drop_column('daily_token_usage', 'user_id')
    # ### end Alembic commands ###
