"""Add auto_commit_at to agent_actions

Revision ID: 84c005084b87
Revises: c76b9f12192e
Create Date: 2026-07-08 16:09:33.993263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c005084b87'
down_revision: Union[str, None] = 'c76b9f12192e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_actions', sa.Column('auto_commit_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_actions', 'auto_commit_at')
    # ### end Alembic commands ###
