"""add goal_id to projects and tasks

Revision ID: 9a468aa9c833
Revises: 0ea3e68e7788
Create Date: 2026-07-06 08:26:53.444527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a468aa9c833'
down_revision: Union[str, None] = '0ea3e68e7788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('goal_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_projects_goal_id'), 'projects', ['goal_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'macro_goals', ['goal_id'], ['id'])
    op.add_column('tasks', sa.Column('goal_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_tasks_goal_id'), 'tasks', ['goal_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'macro_goals', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_goal_id'), table_name='tasks')
    op.drop_column('tasks', 'goal_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_goal_id'), table_name='projects')
    op.drop_column('projects', 'goal_id')
    # ### end Alembic commands ###
