"""Add LLM config to Agent

Revision ID: b218b31f3e21
Revises: d457affebda4
Create Date: 2026-07-09 03:17:46.632225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b218b31f3e21'
down_revision: Union[str, None] = 'd457affebda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('llm_provider', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('openai_chat_model', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('claude_model', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'claude_model')
    op.drop_column('agents', 'openai_chat_model')
    op.drop_column('agents', 'llm_provider')
    # ### end Alembic commands ###
