"""Add addons to subscriptions

Revision ID: b88ba8bcced2
Revises: 755c6a00719d
Create Date: 2026-06-22 22:16:11.131455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88ba8bcced2'
down_revision: Union[str, None] = '755c6a00719d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('addons', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'addons')
    # ### end Alembic commands ###
