"""add fitness goals to health_goals

Revision ID: c72df91f3c61
Revises: 803135c34013
Create Date: 2026-06-21 13:44:20.154292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72df91f3c61'
down_revision: Union[str, None] = '803135c34013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_goals', sa.Column('target_weight', sa.Float(), nullable=True))
    op.add_column('health_goals', sa.Column('target_workouts_per_week', sa.Integer(), nullable=True))
    op.add_column('health_goals', sa.Column('target_water_l_per_day', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_goals', 'target_water_l_per_day')
    op.drop_column('health_goals', 'target_workouts_per_week')
    op.drop_column('health_goals', 'target_weight')
    # ### end Alembic commands ###
