"""add llm configuration to user

Revision ID: d457affebda4
Revises: 898010fa150a
Create Date: 2026-07-09 02:11:30.208264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd457affebda4'
down_revision: Union[str, None] = '898010fa150a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('llm_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('openai_chat_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('claude_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('openai_api_key_encrypted', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('anthropic_api_key_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'anthropic_api_key_encrypted')
    op.drop_column('users', 'openai_api_key_encrypted')
    op.drop_column('users', 'claude_model')
    op.drop_column('users', 'openai_chat_model')
    op.drop_column('users', 'llm_provider')
    # ### end Alembic commands ###
